merge_queue:
  max_parallel_checks: 1

queue_rules:
  - name: vm4-status-reversal-240924
    batch_size: 1
    batch_max_wait_time: "1 second"
    checks_timeout: null
    queue_conditions: true
    merge_conditions:
      - status-success = vm4-security-guard-240924
      - status-success = vm4-hold-guard-240924
    merge_method: merge
